build: false

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "3.8.0"
    PYTHON_ARCH: "32"

    CONAN_REFERENCE: "qca/2.3.0.1"
    CONAN_USERNAME: "rion"
    CONAN_LOGIN_USERNAME: "rion"
    CONAN_CHANNEL: "testing"
    CONAN_UPLOAD: "https://api.bintray.com/conan/rion/common"

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          CONAN_VISUAL_VERSIONS: 16


install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip3.exe install conan --upgrade
  - pip3.exe install conan_package_tools
  - conan user # It creates the conan data directory
  - conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"

test_script:
  - python3 build.py
